modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "createbuildstonetoolkit"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "icon.png"

[[dependencies.createbuildstonetoolkit]]
modId="forge"
mandatory = true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "buildstonetoolkit"
mandatory = true
versionRange = "[${bt_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "create"
mandatory = true
versionRange = "[${create_version},)"
ordering = "NONE"
side = "BOTH"
