modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache License 2.0"

[[mods]]
modId = "createbuildstonetoolkit"
version = "${version}"
displayName = "Create: Buildstone Toolkit"
authors = "HoshinOFW"
description = '''
A Create and Buildstone Toolkit addon aiming to raise the aesthetic ceiling of both mods!
'''
logoFile = "icon.png"

[[dependencies.createbuildstonetoolkit]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "buildstonetoolkit"
type = "required"
versionRange = "[${bt_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbuildstonetoolkit]]
modId = "create"
type = "required"
versionRange = "[${create_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "createbuildstonetoolkit.mixins.json"
